import { useTheme } from '../contexts/ThemeContext';

/**
 * Empty-state illustrations — one per state, brand-derived (The Mark's
 * proportion family: line-only ~30° isometric, ink strokes, exactly one
 * gold element per motif). Two sign systems, never swapped: people speak
 * in the PERSON GLYPH (third head gold), forms speak in the BUBBLE ROW
 * (third bubble gold).
 *
 * Assets: public/empty-art/{light,dark}/ — keyed RGBA pairs pre-rendered
 * per theme (light: plum/gold, dark: cream/gold), so theming is a file
 * pick, not a runtime recolor. Generated by the process.py coverage-fit
 * pipeline (assets/EMPTY-ART-PROMPTS.md has the spec).
 *
 * A11y: aria-hidden — the EmptyState title/description carry the meaning.
 * Static by design: pulse-discipline applies to illustrations too (no
 * loops, nothing for data-motion to quiet).
 */
export type ArtKind = 'students' | 'questions' | 'exams' | 'grading' | 'scheduled' | 'classes';

const ART_FILES: Record<ArtKind, string> = {
  students: '01-students',
  questions: '02-questions',
  exams: '03-active-exams',
  grading: '04-grading',
  scheduled: '05-scheduled',
  classes: '06-classes',
};

interface EmptyStateArtProps {
  kind: ArtKind;
  /** px box — 160 for page-level panels, 96 for compact slots */
  size?: number;
}

export function EmptyStateArt({ kind, size = 160 }: EmptyStateArtProps) {
  const { resolvedTheme } = useTheme();
  return (
    <img
      src={`/empty-art/${resolvedTheme}/${ART_FILES[kind]}.png`}
      alt=""
      aria-hidden="true"
      width={size}
      height={size}
      className="block empty-state-art"
      draggable={false}
    />
  );
}
